### ISSUE TITLE
Won't Compile (Unexpected identifier)

### ISSUE THREAD

**Issue by jiahao-c** [remotemerge/hali#8]
Weird error. TypeScript complains
```
interface Expression {
          ^^^^^^^^^^

SyntaxError: Unexpected identifier
```

Yet the syntax looks perfectly fine to me. Can't figure out why TypeScript produce this error.

Reproduced Here: https://replit.com/@jhcccc/ErrorDescription#index.ts
Code:
```
import Hali from "@remotemerge/hali";

let xml = "<book author='J. K. Rowling'><title>Harry Potter</title></book>";
let parsedXML = new Hali(xml);
```

node version: Tried both on `v10.24.1` and `v14.18.1`
typescript version: `v4.4.4`

**Comment by remotemerge** [comment]
@jiahao-c seems like the issue is from replit.com. I run your script on another sandbox, and it's working as expected.
![image](https://user-images.githubusercontent.com/4655731/140646017-8bc64bc0-6909-4e08-9781-5edc9ae6c92e.png)
The screenshot code is available [here](https://playcode.io/831344).

**Comment by jiahao-c** [comment]
Thanks!
